name: CrossRefCheck with Anchors

on: 
  push:

permissions:
  contents: read

jobs:
  crossref-check-with-anchors:
    uses: Open-Systems-Pharmacology/Workflows/.github/workflows/MarkdownCrossrefCheck_withAnchors.yml@main
    with:
      folder-path: './'
