name: Linkcheck_lychee

on: 
  pull_request:
  push:

permissions:
  contents: read

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: lycheeverse/lychee-action@v1.4.1
      with:
        args: --no-progress --accept 200,403,503 './**/*.md' './**/*.html'
        fail: true
